drop table if exists workers;
create table if not exists workers
(
    id       integer primary key references type auto_increment,
    workerId int,
    rent     double,
    janRent  double,
    febRent  double,
    marRent  double,
    aprRent  double,
    mayRent  double,
    juneRent double,
    julyRent double,
    augRent  double,
    sepRent  double,
    octRent  double,
    novRent  double,
    decRent  double
);
drop table if exists type;
create table if not exists type
(
    bond        double,
    kent        double,
    parlament   double,
    winston     double,
    lm          double,
    malboro     double,
    rotmans     double,
    ld          double,
    fmorris     double,
    aliance     double,
    java        double,
    optima      double,
    petr        double,
    maksim      double,
    crests      double,
    vog         double,
    glamur      double,
    kiss        double,
    esse        double,
    quin        double,
    lady        double,
    mor         double,
    chester     double,
    radopy      double,
    stuardessa  double,
    stolichniye double,
    donskoy     double,
    troyka      double,
    fast        double,
    royal       double,
    manchester  double,
    prestigue   double,
    premier     double,
    cosmos      double,
    next        double,
    magnat      double,
    minsk       double,
    souz        double
);